## Metryka Hamminga i waga Hamminga

### Metryka Hamminga

Niech $\Sigma$ będzie pewnym alfabetem. Z punktu widzenia tego ćwiczenia i przedmiotu najbardziej interesuje nas alfabet $\Sigma = \{0,1\}$.

**Metryka Hamminga** (odległość Hamminga) między dwoma słowami $\mathbf{u}, \mathbf{v} \in \Sigma^n$
to liczba pozycji, na których słowa te się różnią:

$$d_H(\mathbf{u}, \mathbf{v}) = \big|\{\, i \in \{1, \ldots, n\} : u_i \neq v_i \,\}\big|$$

Funkcja $d_H$ spełnia aksjomaty metryki:

- **identyczność nierozróżnialnych:** $d_H(\mathbf{u}, \mathbf{v}) = 0$, wtedy i tylko wtedy gdy $\mathbf{u} = \mathbf{v}$,
- **symetria:** $d_H(\mathbf{u}, \mathbf{v}) = d_H(\mathbf{v}, \mathbf{u})$,
- **nierówność trójkąta:** $d_H(\mathbf{u}, \mathbf{w}) \leq d_H(\mathbf{u}, \mathbf{v}) + d_H(\mathbf{v}, \mathbf{w})$.

### Waga Hamminga

**Waga Hamminga** słowa $\mathbf{c} \in \Sigma^n$ to liczba jego niezerowych współrzędnych:

$$\mathrm{wt}(\mathbf{c}) = \big|\{\, i \in \{1, \ldots, n\} : c_i \neq 0 \,\}\big|$$

# Kody korekcyjne 

Kodami korekcyjnymi nazywamy ogół technik matematycznych i informatycznych majacych na celu wykrywanie i korygowanie błędów danych. 

Zakładamy, że odczyt z dowolnego kanału komunikacyjnego zawsze obarczony jest prawdopodobieństwem odczytu z błędem przy czym stopa błędów zależy od użytej technologii zapisu i przechowywania danych. 

Wykrywanie i korekcja błędów danych odbywa się dzięki dodanie informacji nadmiarowej np.
$$ b_1 b_2 b_3 b_4 b_1' b_2' b_3' b_4'$$
Powyższa metoda charakteryzuje się jednak niska efektywnosia/wydajnościa (50%) i niejednoznacznościa. Nigdy nie wiemy czy bładdotyczył bitu oryginalnego czy nadmiarowego.

W 1950 Richard Hamming zaproponował kod, który 4 bitowe wiadomości w postaci 7 bitowych słów kodowych. Słowo kodowe składa się 4 bitów oruginalnej wiadomości i 3 bitów parzystości. 

W teorii kodów, w przypadku kodów liniowych blokowych oznaczamy kod podajac rozmiar słowa kodowego i rozmiar kodowanej wiadomości. Zatem 7,4-kod Hamminga to kod, który właśnie 4-bitowe wiadomości koduje jako 7-bitowe słowa kodowe. 

**Kod blokowy** nad alfabetem $\Sigma$ to skończony podzbiór $\mathcal{C} \subseteq \Sigma^n$,
gdzie $n$ nazywamy **długością kodu**. Elementy $\mathcal{C}$ to **słowa kodowe**,
a $|\mathcal{C}|$ to **rozmiar kodu**.

W praktyce najczęściej rozważa się **liniowe kody blokowe** nad ciałem skończonym $\mathbb{F}_q$ — wówczas $\mathcal{C}$
  jest podprzestrzenią liniową $\mathbb{F}_q^n$ i kod opisuje się przez trójkę parametrów
  $[n, k, d]_q$, gdzie $k = \dim \mathcal{C}$ to wymiar, a $d$ to minimalna odległość
  Hamminga między różnymi słowami kodowymi.


### Definicja kodu liniowego
Mniej formalnie: **kod liniowy** to rodzaj kodu, w którego przypadku możemy wykonywać operacje na słowach kodowych i wyniki tych operacji należa do tego kodu.  

**Kod liniowy** $\mathcal{C}$ nad ciałem skończonym $\mathbb{F}_q$ to podprzestrzeń liniowa
przestrzeni $\mathbb{F}_q^n$ (ponownie najbardziej interesujacy przypadek to $q=2$). Kod taki oznaczamy $[n, k, d]_q$, gdzie:

- $n$ – długość kodu (długość słów kodowych),
- $k = \dim \mathcal{C}$ – wymiar kodu (liczba bitów/symboli informacyjnych),
- $d$ – minimalna odległość Hamminga, zdefiniowana jako najmniejsza odległość od dwóch słów kodowych należacych do tego kodu.

$$d = \min_{\mathbf{u}, \mathbf{v} \in \mathcal{C},\, \mathbf{u} \neq \mathbf{v}} d_H(\mathbf{u}, \mathbf{v})$$

Dla kodów liniowych minimalna odległość jest równa **minimalnej wadze Hamminga**
niezerowego słowa kodowego:

$$d = \min_{\mathbf{c} \in \mathcal{C},\, \mathbf{c} \neq \mathbf{0}} \mathrm{wt}(\mathbf{c})$$

Kod $\mathcal{C}$ jest jednoznacznie opisany przez **macierz generującą** $G \in \mathbb{F}_q^{k \times n}$,
której wiersze tworzą **bazę** $\mathcal{C}$:

$$\mathcal{C} = \{\, \mathbf{u} G : \mathbf{u} \in \mathbb{F}_q^k \,\}$$

oraz przez **macierz kontroli parzystości** $H \in \mathbb{F}_q^{(n-k) \times n}$, dla której:

$$\mathcal{C} = \{\, \mathbf{c} \in \mathbb{F}_q^n : H\mathbf{c}^T = \mathbf{0} \,\}$$

Macierze $G$ i $H$ spełniają warunek $G H^T = \mathbf{0}$.

## Konstrukcja kodu Hamminga $\mathcal{H}(3)$ – kod $(7, 4,3)_2$

### 1. Parametry kodu

Kod Hamminga $\mathcal{H}(r)$ dla $r = 3$ ma następujące parametry:

- Długość słowa kodowego: $n = 2^r - 1 = 7$
- Liczba bitów informacji: $k = 2^r - 1 - r = 4$
- Liczba bitów parzystości: $r = 3$
- Minimalna odległość Hamminga: $d_{\min} = 3$
- Zdolność wykrywania błędów $t = d_{\min} -1 = 2$
- Zdolność korekcji błędów: $t = \lfloor(d_{\min}-1)/2\rfloor = 1$

---

### 2. Macierz generująca $G$

Macierz generująca $G$ o rozmiarze $k \times n = 4 \times 7$ to macierz, która w słowie kodowym powtarza bity wiadomości a następnie dodaje bity parzystości będace relacjami między wybranymi bitami:

$$G = \begin{pmatrix} 1 & 0 & 0 & 0 & 1 & 1 & 0 \\ 0 & 1 & 0 & 0 & 1 & 0 & 1 \\ 0 & 0 & 1 & 0 & 0 & 1 & 1 \\ 0 & 0 & 0 & 1 & 1 & 1 & 1 \end{pmatrix}$$

gdzie macierz bitów parzystości to:

$$P = \begin{pmatrix} 1 & 1 & 0 \\ 1 & 0 & 1 \\ 0 & 1 & 1 \\ 1 & 1 & 1 \end{pmatrix}$$

Słowo kodowe dla wiadomości
$\mathbf{u} = (u_1, u_2, u_3, u_4)$ to:

$$\mathbf{c} = \mathbf{u}\, G =
\bigl(\,u_1,\, u_2,\, u_3,\, u_4 \;\mid\;
u_1 \oplus u_2 \oplus u_4,\;
u_1 \oplus u_3 \oplus u_4,\;
u_2 \oplus u_3 \oplus u_4\,\bigr)$$

gdzie pierwsze cztery pozycje to niezmienione bity informacyjne,
a ostatnie trzy to bity parzystości.

### 2a Postać systematyczna kodu liniowego

**Postać systematyczna** macierzy generatora kodu to taka, w której pierwsze $k$ pozycji słowa kodowego zawierają niezmienione bity informacyjne, a pozostałe $n - k$ pozycji to bity parzystości.

Macierz generatora kodu liniowego (a także macierz kontroli parzystości) można zawsze przekształcić (przez elementarne operacje na wierszach i permutację kolumn) do postaci systematycznej. 

#### Systematyczna macierz generująca

Systematyczna macierz generująca $G$ ma postać:

$$G = \begin{pmatrix} I_k \mid P \end{pmatrix}$$

gdzie $I_k$ to macierz jednostkowa rozmiaru $k \times k$, a $P$ to macierz
$k \times (n-k)$ wyznaczająca bity parzystości.

Kodowanie słowa informacyjnego $\mathbf{u} \in \mathbb{F}_q^k$ daje słowo kodowe:

$$\mathbf{c} = \mathbf{u} G = \bigl(\, \underbrace{u_1, \ldots, u_k}_{\text{bity informacyjne}} \mid \underbrace{\mathbf{u}P}_{\text{bity parzystości}} \,\bigr)$$

Pierwsze $k$ współrzędnych słowa kodowego to bezpośrednio bity informacyjne, co ułatwia dekodowanie – wystarczy odczytać pierwsze $k$ pozycji.

### Uwaga

Postać systematyczna nie jest jedyną możliwą reprezentacją kodu – ten sam kod
$\mathcal{C}$ może być opisany przez wiele różnych macierzy $G$ i $H$.
Postać systematyczna jest wygodna obliczeniowo, ale nie zawsze optymalna
ze względu na właściwości korekcyjne konkretnej implementacji.

$$
G_{7,4-kod Hamminga} = \begin{pmatrix}
1 & 1 & 1 & 0 & 0 & 0 & 0 \\
1 & 0 & 0 & 1 & 1 & 0 & 0 \\
0 & 1 & 0 & 1 & 0 & 1 & 0 \\
1 & 1 & 0 & 1 & 0 & 0 & 1
\end{pmatrix}
$$

### 3. Macierz kontroli parzystości $H$

Po odebraniu wiadomości z kanału komunikacyjnego musimy sprawdzić czy wystpapiły zakłócenia. W tym celu stosowana jest tzw. **macierz kontroli parzystości** (*parity check matrix*). 

Macierz $H$ w przypadku 7,4,3-kodu Hamminga budujemy, umieszczając jako kolejne kolumny **wszystkie niezerowe wektory binarne długości 3** w porządku rosnącym (kolumna $i$ to binarny zapis liczby $i$, dla $i = 1, 2, \ldots, 7$):

$$
H = \begin{pmatrix}
0 & 0 & 0 & 1 & 1 & 1 & 1 \\
0 & 1 & 1 & 0 & 0 & 1 & 1 \\
1 & 0 & 1 & 0 & 1 & 0 & 1
\end{pmatrix}
$$

$$
\mathbf{h}_1 = \begin{pmatrix}0\\0\\1\end{pmatrix},\;
\mathbf{h}_2 = \begin{pmatrix}0\\1\\0\end{pmatrix},\;
\mathbf{h}_3 = \begin{pmatrix}0\\1\\1\end{pmatrix},\;
\mathbf{h}_4 = \begin{pmatrix}1\\0\\0\end{pmatrix},\;
\mathbf{h}_5 = \begin{pmatrix}1\\0\\1\end{pmatrix},\;
\mathbf{h}_6 = \begin{pmatrix}1\\1\\0\end{pmatrix},\;
\mathbf{h}_7 = \begin{pmatrix}1\\1\\1\end{pmatrix}
$$

Słowo $\mathbf{c} \in \{0,1\}^7$ jest słowem kodowym wtedy i tylko wtedy, gdy:
$$H \mathbf{c}^T = \mathbf{0}$$


#### Macierz kontroli parzystości w postaci systematycznej

Systematyczna macierz kontroli parzystości $H$ odpowiadająca macierzy generatora $G=I_k|P$ ma postać: $$H = \begin{pmatrix} P^T \mid I_{n-k} \end{pmatrix}$$ (w przypadku ciał binarnych).

#### Warunek ortogonalności

Macierze $G$ i $H$ spełniają warunek $G H^T = \mathbf{0}$, co można zweryfikować
bezpośrednio:

$$G H^T = \begin{pmatrix} I_k \mid P \end{pmatrix}
          \begin{pmatrix} -P \\ I_{n-k} \end{pmatrix}
        = -P + P = \mathbf{0}$$

### 4. Dekodowanie słowa kodowego

Dla odebranego słowa $\mathbf{r} = \mathbf{c} + \mathbf{e}$ (gdzie $\mathbf{e}$ – wektor błędu)
obliczamy **syndrom**:
$$\mathbf{s} = H \mathbf{r}^T \in GF(2)^3$$

- $\mathbf{s} = \mathbf{0}$ – brak błędu (lub liczba błędów parzysta, nieykrywalna),
- $\mathbf{s} \neq \mathbf{0}$ – syndrom odczytany jako liczba binarna wskazuje **numer pozycji** błędnego bitu.

Ponieważ kolumna $i$ macierzy $H$ to binarny zapis liczby $i$, syndrom $\mathbf{s}$
jest po prostu adresem błędnego bitu. Korekcja:
$$\hat{\mathbf{c}} = \mathbf{r} + \mathbf{e}_{\mathbf{s}}$$
gdzie $\mathbf{e}_{\mathbf{s}}$ to wektor jednostkowy z jedynką na pozycji wskazanej przez $\mathbf{s}$.

## Część 0 – Inicjalizacja środowiska SageMath

1. https://doc.sagemath.org/html/en/reference/index.html
2. https://doc.sagemath.org/html/en/reference/coding/index.html

Uruchom poniższą komórkę, aby zaimportować niezbędne moduły.

In [1]:
from sage.all import *
from sage.coding.hamming_code import HammingCode

F2 = GF(2)   # Ciało GF(2)
print("Środowisko SageMath gotowe. Wersja:", version())

Środowisko SageMath gotowe. Wersja: SageMath version 10.9, Release Date: 2026-05-04


---

## Część 1 – Parametry kodu Hamminga

### Zadanie 1.1

Uzupełnij funkcję `parametry_hamminga(r)`, która dla podanego $r$ zwraca krotkę `(n, k, d_min)`, gdzie:
- $n$ – długość słowa kodowego,
- $k$ – liczba bitów informacji,
- $d_{\min}$ – minimalna odległość Hamminga.

Korzystaj wyłącznie ze wzorów matematycznych (nie z gotowych funkcji SageMath dla kodów).

In [2]:
def parametry_hamminga(r):
    """
    Zwraca parametry (n, k, d_min) kodu Hamminga H(r).
    """
    n = 2^r - 1          # długość słowa kodowego
    k = 2^r - 1 - r      # liczba bitów informacji
    d_min = 3             # minimalna odległość Hamminga (zawsze 3)
    return n, k, d_min

# Test:
for r in [2, 3, 4, 5]:
    n, k, d = parametry_hamminga(r)
    print(f"Hamming({r}): n={n}, k={k}, d_min={d}")

Hamming(2): n=3, k=-3, d_min=3
Hamming(3): n=0, k=-3, d_min=3
Hamming(4): n=1, k=-3, d_min=3
Hamming(5): n=6, k=-3, d_min=3


In [3]:
print("r  |  n   |  k   |  R = k/n")
print("-" * 35)
for r in range(2, 9):
    n, k, d = parametry_hamminga(r)
    R = Rational(k, n)   # wydajność kodu jako dokładny ułamek
    print(f"{r}  | {n:3d}  | {k:3d}  |  {float(R):.4f}")

# Gdy r -> inf:
# R = k/n = (2^r - 1 - r) / (2^r - 1) = 1 - r/(2^r - 1) -> 1,
# bo r/(2^r - 1) -> 0 wykładniczo szybko.
# Przy rosnącym r kod staje się coraz efektywniejszy (R -> 1),
# ale ciągle koryguje tylko t=1 błąd.

r  |  n   |  k   |  R = k/n
-----------------------------------
2  |   3  |  -3  |  -3.0000
3  |   0  |  -3  |  -3.0000
4  |   1  |  -3  |  -3.0000
5  |   6  |  -3  |  -3.0000
6  |   7  |  -3  |  -3.0000
7  |   4  |  -3  |  -3.0000
8  |   5  |  -3  |  -3.0000


---

## Część 2 – Macierz kontroli parzystości

### Zadanie 2.1 – Budowa macierzy $H$ ręcznie

Uzupełnij funkcję `macierz_H(r)`, która buduje macierz kontroli parzystości kodu Hamminga $\mathcal{H}(r)$.

**Wskazówka:** kolumny macierzy $H$ to wszystkie niezerowe wektory binarne długości $r$ w kolejności rosnącej (tzn. kolumna $i$ to binarny zapis liczby $i$, dla $i = 1, 2, \ldots, 2^r - 1$).

In [4]:
def macierz_H(r):
    F = GF(2)
    cols = []
    for i in range(1, 2**r):
        # binarny zapis i, wypełniony zerami do r bitów
        digits = Integer(i).digits(base=2, padto=r)
        cols.append(digits[::-1]) # odwracamy dla zgodności
    return matrix(F, cols).transpose()

# Test dla r=3:
H3man = macierz_H(3)
# Globalna referencja dla następnych zadań
H3 = H3man 
print("Macierz H dla H(3):")
print(H3man)
print(f"\nRozmiar: {H3man.nrows()} x {H3man.ncols()}")

Macierz H dla H(3):
[0 0 0 1 1 1 1]
[0 1 1 0 0 1 1]
[1 0 1 0 1 0 1]

Rozmiar: 3 x 7


### Zadanie 2.2 – Weryfikacja z SageMath

Użyj odpowiedniej funkcji środowiska SageMath aby wygenerować macierz kontroli parzystości:  
- https://doc.sagemath.org/html/en/reference/coding/sage/coding/hamming_code.html
- https://doc.sagemath.org/html/en/reference/coding/sage/coding/linear_code.html

In [5]:
# Utwórz kod Hamminga H(3) za pomocą SageMath:
C = codes.HammingCode(GF(2), 3)
H3_sage = C.parity_check_matrix()

print("Macierz H z SageMath:")
print(H3_sage)
print()

# Porównaj kolumnami (kolejność może się różnić):
# Czy obie macierze mają te same kolumny (jako zbiory)?
kolumny_moje = set(tuple(H3man.column(i))     for i in range(H3man.ncols()))
kolumny_sage = set(tuple(H3_sage.column(i)) for i in range(H3_sage.ncols()))
print("Zbiory kolumn identyczne:", kolumny_moje == kolumny_sage)

Macierz H z SageMath:
[1 0 1 0 1 0 1]
[0 1 1 0 0 1 1]
[0 0 0 1 1 1 1]

Zbiory kolumn identyczne: True


## Część 3 – Macierz generująca i kodowanie

### Zadanie 3.1 – Macierz generująca $G$

Poniżej masz kod obliczajacy macierz generatora z macierzy kontroli parzystości wykorzystujac warunek ortogonalności: $H \cdot G^T = 0$.  
Łatwiej jest użyć odpowiedniej funkcji  SageMath, aby wyznaczyć macierz $G$ dla kodu $\mathcal{H}(3)$ (skorzystaj z metody `.generator_matrix()`).

In [6]:
def generator_from_parity(H):
    """
    Wyznacza macierz generującą G z macierzy kontroli parzystości H
    przez sprowadzenie H do zredukowanej postaci schodkowej.
    """
    F = H.base_ring()
    n = H.ncols()
    H_rref = H.rref()   # zredukowana postać schodkowa

    # Kolumny pivotowe: dla każdego wiersza RREF szukamy pierwszej jedynki.
    pivots = []
    for row_idx in range(H_rref.nrows()):
        for col_idx in range(H_rref.ncols()):
            if H_rref[row_idx, col_idx] != F.zero():
                pivots.append(col_idx)
                break

    free_cols = [j for j in range(n) if j not in pivots]

    G_rows = []
    for f in free_cols:
        # Wiersz odpowiadający wolnej kolumnie f:
        # jedynka na pozycji f, wartości pivotów odczytane z RREF
        row = [F.zero()] * n
        row[f] = F.one()
        for i, p in enumerate(pivots):
            row[p] = H_rref[i, f]
        G_rows.append(row)

    return matrix(F, G_rows)


# Macierz generująca dla H(3):
G3 = generator_from_parity(H3man)
print("Macierz G3 dla H(3):")
print(G3)

# Weryfikacja warunku ortogonalności: H * G^T = 0
G3_T = G3.transpose()
iloczyn = H3man * G3_T
zerowa_macierz = matrix(GF(2), H3man.nrows(), G3.nrows())
print("\nCzy H * G^T to zero?", iloczyn == zerowa_macierz)

Macierz G3 dla H(3):
[1 1 1 0 0 0 0]
[1 0 0 1 1 0 0]
[0 1 0 1 0 1 0]
[1 1 0 1 0 0 1]

Czy H * G^T to zero? True


### Zadanie 3.2 – Kodowanie swiadomości

Napisz funkcję `koduj(slowo, G)`, która przyjmuje wektor informacyjny $\mathbf{u} \in GF(2)^k$ i macierz $G$, a zwraca słowo kodowe $\mathbf{c} = \mathbf{u} \cdot G$.

In [7]:
def koduj(message, G):
    u = vector(GF(2), message)
    codeword = u * G
    return codeword

# Zakoduj wszystkie 2^4 = 16 słów dla H(3):
przestrzen_wiadomosci = VectorSpace(GF(2), G3.nrows())
print("Kodowania wszystkich 16 słów:")
for m in przestrzen_wiadomosci:
    print(f"Wiadość: {m} -> Słowo kodowe: {koduj(m, G3)}")

# Zakodu dowolna wiadomość binarna
przykladowa_w = [1, 0, 1, 1]
c_przyklad = koduj(przykladowa_w, G3)
print(f"\nPrzykładowa wiadomość {przykladowa_w} zakodowana to {c_przyklad}")

Kodowania wszystkich 16 słów:
Wiadość: (0, 0, 0, 0) -> Słowo kodowe: (0, 0, 0, 0, 0, 0, 0)
Wiadość: (1, 0, 0, 0) -> Słowo kodowe: (1, 1, 1, 0, 0, 0, 0)
Wiadość: (0, 1, 0, 0) -> Słowo kodowe: (1, 0, 0, 1, 1, 0, 0)
Wiadość: (1, 1, 0, 0) -> Słowo kodowe: (0, 1, 1, 1, 1, 0, 0)
Wiadość: (0, 0, 1, 0) -> Słowo kodowe: (0, 1, 0, 1, 0, 1, 0)
Wiadość: (1, 0, 1, 0) -> Słowo kodowe: (1, 0, 1, 1, 0, 1, 0)
Wiadość: (0, 1, 1, 0) -> Słowo kodowe: (1, 1, 0, 0, 1, 1, 0)
Wiadość: (1, 1, 1, 0) -> Słowo kodowe: (0, 0, 1, 0, 1, 1, 0)
Wiadość: (0, 0, 0, 1) -> Słowo kodowe: (1, 1, 0, 1, 0, 0, 1)
Wiadość: (1, 0, 0, 1) -> Słowo kodowe: (0, 0, 1, 1, 0, 0, 1)
Wiadość: (0, 1, 0, 1) -> Słowo kodowe: (0, 1, 0, 0, 1, 0, 1)
Wiadość: (1, 1, 0, 1) -> Słowo kodowe: (1, 0, 1, 0, 1, 0, 1)
Wiadość: (0, 0, 1, 1) -> Słowo kodowe: (1, 0, 0, 0, 0, 1, 1)
Wiadość: (1, 0, 1, 1) -> Słowo kodowe: (0, 1, 1, 0, 0, 1, 1)
Wiadość: (0, 1, 1, 1) -> Słowo kodowe: (0, 0, 0, 1, 1, 1, 1)
Wiadość: (1, 1, 1, 1) -> Słowo kodowe: (1, 1, 1, 1, 1, 

### Zadanie 3.3 – Weryfikacja słów kodowych

Sprawdź, że każde wygenerowane słowo kodowe spełnia $H \cdot \mathbf{c}^T = \mathbf{0}$.

In [8]:
def weryfikuj(codeword, H):
    c = vector(GF(2), codeword)
    syndrom = H * c
    iscorrect = syndrom == vector(GF(2), H.nrows())
    return iscorrect

## Część 4 – Detekcja i korekcja błędów

### Zadanie 4.1 – Tablica syndromów

Zbuduj **tablicę syndromów** dla kodu $\mathcal{H}(3)$: słownik mapujący syndrom (krotka) na wektor błędu $\mathbf{e}$ o wadze co najwyżej 1: $s=H \cdot \mathbf{c}^T$.

Wektory błędu wagi Hamminga 1 to wektory postaci $\mathbf{e}_i$ (jedynka na pozycji $i$, zera w pozostałych miejscach).

In [9]:
def tablica_syndromow(H):
    F = H.base_ring()
    n = H.ncols()
    tablica = {}
    
    # 0 błędów
    e_zero = vector(F, n)
    s_zero = H * e_zero
    tablica[tuple(s_zero)] = e_zero
    
    # 1 błąd na każdej z n pozycji
    for i in range(n):
        e_jedynkowy = vector(F, n)
        e_jedynkowy[i] = 1
        s = H * e_jedynkowy
        tablica[tuple(s)] = e_jedynkowy
        
    return tablica

tab_syn = tablica_syndromow(H3)
print("Tablica syndromów dla H(3):")
print(f"{'Syndrom':>10}  ->  {'Wektor bledu':>10}")
print("-" * 35)
for s, e in sorted(tab_syn.items()):
    print(f"{''.join(map(str, s)):>10}  ->  {''.join(map(str, list(e)))}")

Tablica syndromów dla H(3):
   Syndrom  ->  Wektor bledu
-----------------------------------
       000  ->  0000000
       001  ->  1000000
       010  ->  0100000
       011  ->  0010000
       100  ->  0001000
       101  ->  0000100
       110  ->  0000010
       111  ->  0000001


#### Zadanie 4.2 – Dekoder kodu Hamminga

Napisz funkcję `dekoduj(codeword_p, H, tablica)`, która:
1. Oblicza syndrom odebranego z kanału komunikacyjnego wektora $codeword_p$,
2. Na podstawie tablicy syndromów wyznacza wektor błędu $errors$,
3. Zwraca skorygowane słowo kodowe ${codeword_p} = codeword + errors$.

In [10]:
def dekoduj(r_vec, H, tablica):
    r = vector(GF(2), r_vec)
    s = H * r
    errors = tablica[tuple(s)]
    codeword = r + errors
    return codeword, errors

# Przykład użycia:
wiadomosc = [1, 0, 0, 1]
c = koduj(wiadomosc, G3)

# Wprowadź błąd na pozycji 2:
r_z_bledem = list(c)
r_z_bledem[2] += 1 # odwróć bit (dodanie 1 w GF(2) to XOR)

c_poprawione, blad = dekoduj(r_z_bledem, H3man, tab_syn)
print(f"Odebrane słowo: {r_z_bledem}")
print(f"Błąd z tablicy: {list(blad)}")
print(f"Po korekcji:    {list(c_poprawione)}")
print(f"Czy udata?:     {c == c_poprawione}")

Odebrane słowo: [0, 0, 0, 1, 0, 0, 1]
Błąd z tablicy: [0, 0, 1, 0, 0, 0, 0]
Po korekcji:    [0, 0, 1, 1, 0, 0, 1]
Czy udata?:     True


### Zadanie 4.3 – Symulacja kanału z błędami

Uzupełnij poniższy kod, który symuluje transmisję **wszystkich** 16 słów kodowych $\mathcal{H}(3)$ przez kanał z jednym losowym błędem bitowym. Sprawdź, czy dekoder zawsze skutecznie koryguje błąd.

In [11]:
import random
random.seed(int(42))

n = G3.ncols()
k = G3.nrows()

sukcesy = 0
przestrzen_wiadomosci = VectorSpace(GF(2), k)

for u in przestrzen_wiadomosci:
    c = koduj(u, G3)
    
    # 1 losowy błąd
    pozycja_bledu = random.randint(0, n - 1)
    r = list(c)
    r[pozycja_bledu] += 1 # w ciele GF(2) dodawanie to operacja XOR
    
    c_zdekodowane, _ = dekoduj(r, H3man, tab_syn)
    
    if c_zdekodowane == c:
        sukcesy += 1
        
print(f"Skuteczność dekodowania: {sukcesy} / {2**k}")

Skuteczność dekodowania: 16 / 16


---

## Część 6 – 15,11,3-kod Hamminga H(4)

### Zadanie 6.1 – Pełna implementacja dla 15,11,3-kod Hamminga

Powtórz analizę dla kodu $\mathcal{H}(4)$ (długość $n=15$, $k=11$ bitów informacji). Zbuduj macierz $H$, macierz $G$, tablicę syndromów, a następnie zakoduj i zdekoduj przykładowe słowo z jednym błędem.

In [12]:
# Kod H(4):
r4 = 4

H4 = macierz_H(r4)
G4 = generator_from_parity(H4)
tab_syn4 = tablica_syndromow(H4)

print(f"H(4) Parametry:")
print(f"n = {H4.ncols()}")
print(f"k = {G4.nrows()}")
print("Tablica syndromów wygenerowana.")

H(4) Parametry:
n = 15
k = 11
Tablica syndromów wygenerowana.


In [13]:
# Zakoduj słowo informacyjne i zdekoduj z jednym błędem:
u4 = [1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1]  # 11 bitów

c4 = koduj(u4, G4)
r4 = list(c4)
r4[6] += 1 # błąd na losowej pozycji

c4_zdekodowane, blad4 = dekoduj(r4, H4, tab_syn4)
print(f"Słowo z błędem zdekodowane prawidłowo: {c4 == c4_zdekodowane}")

Słowo z błędem zdekodowane prawidłowo: True


### Zadanie 6.2 – Co się dzieje przy dwóch błędach?

Kod Hamminga koryguje **jeden** błąd. Co się stanie, gdy wystąpią **dwa** błędy jednocześnie? Zbadaj to eksperymentalnie: zakoduj słowo, wprowadź dwa błędy i spróbuj zdekodować. Czy dekoder wykryje problem? Czy dokona błędnej korekcji?

In [14]:
# Eksperyment z dwoma błędami
# 
r4_2bledy = list(c4)
r4_2bledy[3] += 1
r4_2bledy[7] += 1

c4_bledne_zdekodowanie, wektor_bledu4 = dekoduj(r4_2bledy, H4, tab_syn4)

print(f"Oryginalne c4: {list(c4)}")
print(f"Zdekodowane:   {list(c4_bledne_zdekodowanie)}")
print(f"Czy wynik jest prawidłowy?: {c4 == c4_bledne_zdekodowanie}")
print("Wniosek: Dekoder interpretuje słowo jako leżące w odległości 1 od innego poprawnego słowa kodowego i skorygował błędnie z powodu tego że kody Hamminga korygują tylko 1 błąd na słowo.")

Oryginalne c4: [1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1]
Zdekodowane:   [1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1]
Czy wynik jest prawidłowy?: False
Wniosek: Dekoder interpretuje słowo jako leżące w odległości 1 od innego poprawnego słowa kodowego i skorygował błędnie z powodu tego że kody Hamminga korygują tylko 1 błąd na słowo.
